"""ensure_date_collumns_nullable

Revision ID: 065f043a38d5
Revises: f81fdc0ecab1
Create Date: 2025-06-26 13:37:16.606782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '065f043a38d5'
down_revision = 'f81fdc0ecab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AirCompanyInvoiceReport', 'FlightDate',
                   existing_type=sa.Date(),
                   nullable=True,
                   schema='ccs')
    op.alter_column('AirCompanyInvoiceReport', 'InvoiceDate',
                   existing_type=sa.Date(),
                   nullable=True,
                   schema='ccs')
    op.alter_column('AirCompanyInvoiceReport', 'PaidDate',
                   existing_type=sa.Date(),
                   nullable=True,
                   schema='ccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AirCompanyInvoiceReport', 'PaidDate',
                   existing_type=sa.Date(),
                   nullable=False,
                   schema='ccs')
    op.alter_column('AirCompanyInvoiceReport', 'InvoiceDate',
                   existing_type=sa.Date(),
                   nullable=False,
                   schema='ccs')
    op.alter_column('AirCompanyInvoiceReport', 'FlightDate',
                   existing_type=sa.Date(),
                   nullable=False,
                   schema='ccs')
    # ### end Alembic commands ###
