"""correct InvoiceHistory table

Revision ID: 133bffe21e3e
Revises: 808503fb277b
Create Date: 2025-01-28 15:41:36.852440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '133bffe21e3e'
down_revision = '808503fb277b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InvoiceHistory',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('BrdFac', sa.String(length=20), nullable=True),
    sa.Column('BrdFltDt', sa.Date(), nullable=True),
    sa.Column('BrdFltNr', sa.Integer(), nullable=True),
    sa.Column('OpCd', sa.Integer(), nullable=True),
    sa.Column('SrvDptStaCd', sa.String(length=10), nullable=True),
    sa.Column('SrvArrStaCd', sa.String(length=10), nullable=True),
    sa.Column('SrvFltNr', sa.Integer(), nullable=True),
    sa.Column('SrvFltDt', sa.Date(), nullable=True),
    sa.Column('Cos', sa.String(length=10), nullable=True),
    sa.Column('Psg', sa.Integer(), nullable=True),
    sa.Column('Meal', sa.Integer(), nullable=True),
    sa.Column('Tray', sa.Integer(), nullable=True),
    sa.Column('Total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Paid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Variance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('GrandTotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('OvdInd', sa.String(length=10), nullable=True),
    sa.Column('IvcPcsDt', sa.Date(), nullable=True),
    sa.Column('IvcDbsDt', sa.Date(), nullable=True),
    sa.Column('Org', sa.Integer(), nullable=True),
    sa.Column('IvcSeqNr', sa.Integer(), nullable=True),
    sa.Column('IvcCreDt', sa.Date(), nullable=True),
    sa.Column('Comments', sa.String(length=255), nullable=True),
    sa.Column('LineSeqNr', sa.Integer(), nullable=True),
    sa.Column('Item', sa.Integer(), nullable=True),
    sa.Column('ActAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ActQty', sa.Integer(), nullable=True),
    sa.Column('SchAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('SchQty', sa.Integer(), nullable=True),
    sa.Column('ActLbrAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('SchLbrAmt', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ItemDesc', sa.String(length=200), nullable=True),
    sa.Column('PktTyp', sa.String(length=40), nullable=True),
    sa.Column('PktNr', sa.Integer(), nullable=True),
    sa.Column('PktNm', sa.String(length=50), nullable=True),
    sa.Column('PktVar', sa.Integer(), nullable=True),
    sa.Column('CourceName', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
def downgrade():
    op.drop_table('InvoiceHistory', schema='ccs')
    # ### end Alembic commands ###
