"""Nova tabela DocumentoAnexo schema dlm

Revision ID: 230295b0b722
Revises: 3104252a6bff
Create Date: 2024-10-24 14:38:19.654421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '230295b0b722'
down_revision = '3104252a6bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentoAnexo',
    sa.Column('Id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('IdDocumento', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('IdAnexo', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['IdDocumento'], ['dlm.Documento.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentoAnexo', schema='dlm')
    # ### end Alembic commands ###
