"""Criação coluna IdUsuarioCriacao na tabela Documento

Revision ID: 26ed6c4b608d
Revises: 230295b0b722
Create Date: 2024-11-11 09:16:56.776071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26ed6c4b608d'
down_revision = '230295b0b722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    # op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    # op.drop_table('django_admin_log')
    # op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    # op.drop_table('auth_permission')
    # op.drop_table('t_e')
    # op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    # op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    # op.drop_table('django_session')
    # op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    # op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    # op.drop_table('auth_user_user_permissions')
    # op.drop_index('ix_ItemEssencial_CodigoProduto', table_name='ItemEssencial')
    # op.drop_index('ix_ItemEssencial_IdEmpresa', table_name='ItemEssencial')
    # op.drop_table('ItemEssencial')
    # op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    # op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    # op.drop_table('auth_group_permissions')
    # op.drop_table('ConsultaCnpj')
    # op.drop_table('Eventos')
    # op.drop_table('SystemMessage')
    # op.drop_table('PerfilAplicacaoFuncao')
    # op.drop_table('InscricoesEstaduais')
    # op.drop_index('ix_ClienteTopicoBi_IdCliente', table_name='ClienteTopicoBi')
    # op.drop_table('ClienteTopicoBi')
    # op.drop_index('ix_Execucao_IdEmpresa', table_name='Execucao')
    # op.drop_table('Execucao')
    # op.drop_table('IcmsPer')
    # op.drop_index('ix_UsuarioDashboardBi_IdUsuario', table_name='UsuarioDashboardBi')
    # op.drop_table('UsuarioDashboardBi')
    # op.drop_table('ArquivoUploadEmpresa1')
    # op.drop_index('ix_UsuarioEmpresa_IdEmpresa', table_name='UsuarioEmpresa')
    # op.drop_table('UsuarioEmpresa')
    # op.drop_table('django_content_type')
    # op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    # op.drop_table('auth_user')
    # op.drop_table('django_migrations')
    # op.drop_table('Perfil')
    # op.drop_table('UserPerfilPermission')
    # op.drop_index('enquadramento_idx', table_name='Enquadramento')
    # op.drop_table('Enquadramento')
    # op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    # op.drop_table('auth_group')
    # op.drop_index('ix_ClienteDashboardBi_IdCliente', table_name='ClienteDashboardBi')
    # op.drop_table('ClienteDashboardBi')
    # op.drop_index('cst_tributo_idx', table_name='CST')
    # op.drop_table('CST')
    # op.drop_table('DashboardBi')
    # op.drop_index('ix_IncomingEmails_IdEmpresa', table_name='IncomingEmails')
    # op.drop_index('ix_IncomingEmails_TipoNota', table_name='IncomingEmails')
    # op.drop_table('IncomingEmails')
    # op.drop_table('AplicacaoFuncao')
    # op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    # op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    # op.drop_table('auth_user_groups')
    # op.drop_table('EventoNota')
    # op.drop_table('AnaliseSpedMessage')
    # op.drop_table('UserPerfil')
    # op.drop_table('Produto')
    # op.drop_index('ix_ArquivoUploadEmpresa_IdEmpresa', table_name='ArquivoUploadEmpresa')
    # op.create_index(op.f('ix_public_ArquivoUploadEmpresa_IdEmpresa'), 'ArquivoUploadEmpresa', ['IdEmpresa'], unique=False, schema='public')
    # op.drop_constraint('ArquivoUploadEmpresa_IdEmpresa_fkey', 'ArquivoUploadEmpresa', type_='foreignkey')
    # op.drop_constraint('ArquivoUploadEmpresa_IdUsuarioAlteracao_fkey', 'ArquivoUploadEmpresa', type_='foreignkey')
    # op.create_foreign_key(None, 'ArquivoUploadEmpresa', 'Empresa', ['IdEmpresa'], ['Id'], source_schema='public')
    # op.create_foreign_key(None, 'ArquivoUploadEmpresa', 'User', ['IdUsuarioAlteracao'], ['Id'], source_schema='public')
    # op.drop_index('ix_CategoriaArquivo_IdCategoria', table_name='CategoriaArquivo')
    # op.create_index(op.f('ix_public_CategoriaArquivo_IdCategoria'), 'CategoriaArquivo', ['IdCategoria'], unique=False, schema='public')
    # op.drop_constraint('CategoriaArquivo_IdCategoria_fkey', 'CategoriaArquivo', type_='foreignkey')
    # op.create_foreign_key(None, 'CategoriaArquivo', 'CategoriaEmpresa', ['IdCategoria'], ['Id'], source_schema='public')
    # op.alter_column('StoredFiles', 'TipoDoArquivo',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    # op.alter_column('StoredFiles', 'NomeDoArquivo',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Text(),
    #            existing_nullable=False)
    # op.alter_column('StoredFiles', 'key',
    #            existing_type=sa.VARCHAR(length=500),
    #            type_=sa.Text(),
    #            existing_nullable=True)
    # op.drop_index('ix_StoredFiles_DataInicio', table_name='StoredFiles')
    # op.drop_index('ix_StoredFiles_ErrorMessage', table_name='StoredFiles')
    # op.drop_index('ix_StoredFiles_IdEmpresa', table_name='StoredFiles')
    # op.drop_index('ix_StoredFiles_NomeDoArquivo', table_name='StoredFiles')
    # op.drop_index('ix_StoredFiles_TipoDoArquivo', table_name='StoredFiles')
    # op.drop_index('ix_StoredFiles_TipoNota', table_name='StoredFiles')
    # op.create_index(op.f('ix_public_StoredFiles_IdEmpresa'), 'StoredFiles', ['IdEmpresa'], unique=False, schema='public')
    # op.drop_constraint('StoredFiles_IdEmpresa_fkey', 'StoredFiles', type_='foreignkey')
    # op.drop_constraint('StoredFiles_IdExecucao_fkey', 'StoredFiles', type_='foreignkey')
    # op.drop_constraint('StoredFiles_IdUsuarioAlteracao_fkey', 'StoredFiles', type_='foreignkey')
    # op.create_foreign_key(None, 'StoredFiles', 'User', ['IdUsuarioAlteracao'], ['Id'], source_schema='public')
    # op.create_foreign_key(None, 'StoredFiles', 'Empresa', ['IdEmpresa'], ['Id'], source_schema='public')
    # op.drop_column('StoredFiles', 'ChaveNota')
    # op.drop_column('StoredFiles', 'DataInicio')
    # op.drop_column('StoredFiles', 'ErrorMessage')
    # op.drop_column('StoredFiles', 'TipoNota')
    # op.drop_column('StoredFiles', 'Transferido')
    # op.drop_column('StoredFiles', 'IdExecucao')
    op.add_column('Documento', sa.Column('IdUsuarioCriacao', sa.UUID(), nullable=True), schema='dlm')
    op.create_foreign_key(None, 'Documento', 'User', ['IdUsuarioCriacao'], ['Id'], source_schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Documento', schema='dlm', type_='foreignkey')
    op.drop_column('Documento', 'IdUsuarioCriacao', schema='dlm')
    # op.add_column('StoredFiles', sa.Column('IdExecucao', sa.UUID(), autoincrement=False, nullable=True))
    # op.add_column('StoredFiles', sa.Column('Transferido', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.add_column('StoredFiles', sa.Column('TipoNota', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    # op.add_column('StoredFiles', sa.Column('ErrorMessage', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # op.add_column('StoredFiles', sa.Column('DataInicio', sa.DATE(), autoincrement=False, nullable=True))
    # op.add_column('StoredFiles', sa.Column('ChaveNota', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'StoredFiles', schema='public', type_='foreignkey')
    # op.drop_constraint(None, 'StoredFiles', schema='public', type_='foreignkey')
    # op.create_foreign_key('StoredFiles_IdUsuarioAlteracao_fkey', 'StoredFiles', 'User', ['IdUsuarioAlteracao'], ['Id'])
    # op.create_foreign_key('StoredFiles_IdExecucao_fkey', 'StoredFiles', 'Execucao', ['IdExecucao'], ['Id'])
    # op.create_foreign_key('StoredFiles_IdEmpresa_fkey', 'StoredFiles', 'Empresa', ['IdEmpresa'], ['Id'])
    # op.drop_index(op.f('ix_public_StoredFiles_IdEmpresa'), table_name='StoredFiles', schema='public')
    # op.create_index('ix_StoredFiles_TipoNota', 'StoredFiles', ['TipoNota'], unique=False)
    # op.create_index('ix_StoredFiles_TipoDoArquivo', 'StoredFiles', ['TipoDoArquivo'], unique=False)
    # op.create_index('ix_StoredFiles_NomeDoArquivo', 'StoredFiles', ['NomeDoArquivo'], unique=False)
    # op.create_index('ix_StoredFiles_IdEmpresa', 'StoredFiles', ['IdEmpresa'], unique=False)
    # op.create_index('ix_StoredFiles_ErrorMessage', 'StoredFiles', ['ErrorMessage'], unique=False)
    # op.create_index('ix_StoredFiles_DataInicio', 'StoredFiles', ['DataInicio'], unique=False)
    # op.alter_column('StoredFiles', 'key',
    #            existing_type=sa.Text(),
    #            type_=sa.VARCHAR(length=500),
    #            existing_nullable=True)
    # op.alter_column('StoredFiles', 'NomeDoArquivo',
    #            existing_type=sa.Text(),
    #            type_=sa.VARCHAR(length=255),
    #            existing_nullable=False)
    # op.alter_column('StoredFiles', 'TipoDoArquivo',
    #            existing_type=sa.String(length=50),
    #            type_=sa.VARCHAR(length=255),
    #            existing_nullable=True)
    # op.drop_constraint(None, 'CategoriaArquivo', schema='public', type_='foreignkey')
    # op.create_foreign_key('CategoriaArquivo_IdCategoria_fkey', 'CategoriaArquivo', 'CategoriaEmpresa', ['IdCategoria'], ['Id'])
    # op.drop_index(op.f('ix_public_CategoriaArquivo_IdCategoria'), table_name='CategoriaArquivo', schema='public')
    # op.create_index('ix_CategoriaArquivo_IdCategoria', 'CategoriaArquivo', ['IdCategoria'], unique=False)
    # op.drop_constraint(None, 'ArquivoUploadEmpresa', schema='public', type_='foreignkey')
    # op.drop_constraint(None, 'ArquivoUploadEmpresa', schema='public', type_='foreignkey')
    # op.create_foreign_key('ArquivoUploadEmpresa_IdUsuarioAlteracao_fkey', 'ArquivoUploadEmpresa', 'User', ['IdUsuarioAlteracao'], ['Id'])
    # op.create_foreign_key('ArquivoUploadEmpresa_IdEmpresa_fkey', 'ArquivoUploadEmpresa', 'Empresa', ['IdEmpresa'], ['Id'])
    # op.drop_index(op.f('ix_public_ArquivoUploadEmpresa_IdEmpresa'), table_name='ArquivoUploadEmpresa', schema='public')
    # op.create_index('ix_ArquivoUploadEmpresa_IdEmpresa', 'ArquivoUploadEmpresa', ['IdEmpresa'], unique=False)
    # op.create_table('Produto',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('IdEmpresa', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Codigo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    # sa.Column('Pid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('Familia', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('CodAuxiliar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('Icms', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('Ncm', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('Descricao', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    # sa.Column('UniMedida', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('SegunUm', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('FatorConv', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('TipoConver', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('Tipo', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('ArmPadrao', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('Conta', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('CtaCredito', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('CtaDebito', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('Ipi', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('Iss', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('Origem', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('RetemPis', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('RetemCofins', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('RetemCsll', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    # sa.Column('SFamilia', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('EnqIpi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('Cest', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    # sa.Column('TipoServico', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('NatRend', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('Codigo;PID;Familia;Cod Auxiliar;ICMS;NCM;Descricao;Unid. Medida', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdEmpresa'], ['Empresa.Id'], name='Produto_IdEmpresa_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='Produto_pkey')
    # )
    # op.create_table('UserPerfil',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdUser', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('IdPerfil', sa.UUID(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdPerfil'], ['Perfil.Id'], name='UserPerfil_IdPerfil_fkey'),
    # sa.ForeignKeyConstraint(['IdUser'], ['User.Id'], name='UserPerfil_IdUser_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='UserPerfil_pkey')
    # )
    # op.create_table('AnaliseSpedMessage',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('IdLinha', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('Registro', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    # sa.Column('IdSysMessage', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('Descricao', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('Confiabilidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('NcmPred', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    # sa.Column('AliqPred', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdSysMessage'], ['SystemMessage.Id'], name='AnaliseSpedMessage_IdSysMessage_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='AnaliseSpedMessage_pkey')
    # )
    # op.create_table('EventoNota',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('IdEvento', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('IdNota', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('EventoLido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdEmpresa', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdEmpresa'], ['nota_avulsa.empresa.id'], name='EventoNota_IdEmpresa_fkey'),
    # sa.ForeignKeyConstraint(['IdEvento'], ['Eventos.Id'], name='EventoNota_IdEvento_fkey'),
    # sa.ForeignKeyConstraint(['IdNota'], ['nota_avulsa.nota.id_nota_entrada'], name='EventoNota_IdNota_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='EventoNota_pkey')
    # )
    # op.create_table('auth_user_groups',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    # sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    # )
    # op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    # op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    # op.create_table('AplicacaoFuncao',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Aplicacao', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('Funcao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('Id', name='AplicacaoFuncao_pkey')
    # )
    # op.create_table('IncomingEmails',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('EmailOrigem', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('ChaveNota', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('TipoNota', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    # sa.Column('StatusUpload', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    # sa.Column('IdEmpresa', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdEmpresa'], ['nota_avulsa.empresa.id'], name='IncomingEmails_IdEmpresa_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='IncomingEmails_pkey')
    # )
    # op.create_index('ix_IncomingEmails_TipoNota', 'IncomingEmails', ['TipoNota'], unique=False)
    # op.create_index('ix_IncomingEmails_IdEmpresa', 'IncomingEmails', ['IdEmpresa'], unique=False)
    # op.create_table('DashboardBi',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Url', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('Nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('Id', name='DashboardBi_pkey')
    # )
    # op.create_table('CST',
    # sa.Column('Tributo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('Cst', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('Descricao', sa.TEXT(), autoincrement=False, nullable=True)
    # )
    # op.create_index('cst_tributo_idx', 'CST', ['Tributo', 'Cst'], unique=False)
    # op.create_table('ClienteDashboardBi',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('IdCliente', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('DataInicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataFim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('Dashboard', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('Url', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.Id'], name='ClienteDashboardBI_IdCliente_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='ClienteDashboardBI_pkey')
    # )
    # op.create_index('ix_ClienteDashboardBi_IdCliente', 'ClienteDashboardBi', ['IdCliente'], unique=False)
    # op.create_table('auth_group',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    # sa.UniqueConstraint('name', name='auth_group_name_key'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    # op.create_table('Enquadramento',
    # sa.Column('codigo', sa.NUMERIC(), autoincrement=False, nullable=True),
    # sa.Column('grupo', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    # sa.Column('Cst', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('Descricao', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('Cfop', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    # sa.Column('Cst1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    # sa.Column('Municipio', sa.VARCHAR(length=500), autoincrement=False, nullable=True)
    # )
    # op.create_index('enquadramento_idx', 'Enquadramento', ['codigo'], unique=False)
    # op.create_table('UserPerfilPermission',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdUsuario', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('Aplicacao', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('Permissao', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdUsuario'], ['User.Id'], name='UserPerfilPermission_IdUsuario_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='UserPerfilPermission_pkey')
    # )
    # op.create_table('Perfil',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdGroup', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('Perfil', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('Mtp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('Elm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('UpDoc', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('SolDoc', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('Catg', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('Mbi', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('NfAv', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('CadDad', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('Erp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdGroup'], ['Group.Id'], name='Perfil_IdGroup_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='Perfil_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('django_migrations',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    # )
    # op.create_table('auth_user',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    # sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    # sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    # sa.UniqueConstraint('username', name='auth_user_username_key'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    # op.create_table('django_content_type',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    # sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('UsuarioEmpresa',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdEmpresa', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('IdUsuario', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('ReceiveEmail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdEmpresa'], ['Empresa.Id'], name='UsuarioEmpresa_IdEmpresa_fkey'),
    # sa.ForeignKeyConstraint(['IdUsuario'], ['User.Id'], name='UsuarioEmpresa_IdUsuario_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='UsuarioEmpresa_pkey')
    # )
    # op.create_index('ix_UsuarioEmpresa_IdEmpresa', 'UsuarioEmpresa', ['IdEmpresa'], unique=False)
    # op.create_table('ArquivoUploadEmpresa1',
    # sa.Column('IdEmpresa', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdUsuarioAlteracao', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('TipoArquivo', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('Qtd', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('Obs', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('DataInicio', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('DataFim', sa.DATE(), autoincrement=False, nullable=True),
    # sa.Column('Extensao', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    # )
    # op.create_table('UsuarioDashboardBi',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('IdUsuario', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('DataInicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataFim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('Dashboard', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('Url', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['IdUsuario'], ['User.Id'], name='UsuarioDashboardBi_IdUsuario_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='UsuarioDashboardBi_pkey')
    # )
    # op.create_index('ix_UsuarioDashboardBi_IdUsuario', 'UsuarioDashboardBi', ['IdUsuario'], unique=False)
    # op.create_table('IcmsPer',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdUsuarioAlteracao', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('UfOrigem', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    # sa.Column('UfDestino', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    # sa.Column('IcmsPer', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], name='ICMS_PER_IdUsuarioAlteracao_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='ICMS_PER_pkey')
    # )
    # op.create_table('Execucao',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('ExecucaoFinalizada', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('QtdeArquivo', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    # sa.Column('IdEmpresa', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('IdUsuario', sa.UUID(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdEmpresa'], ['Empresa.Id'], name='Execucao_IdEmpresa_fkey'),
    # sa.ForeignKeyConstraint(['IdUsuario'], ['User.Id'], name='Execucao_IdUsuario_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='Execucao_pkey')
    # )
    # op.create_index('ix_Execucao_IdEmpresa', 'Execucao', ['IdEmpresa'], unique=False)
    # op.create_table('ClienteTopicoBi',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('IdCliente', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('DataInicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataFim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('Topico', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('Url', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['IdCliente'], ['Cliente.Id'], name='ClienteTopicoBi_IdCliente_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='ClienteTopicoBi_pkey')
    # )
    # op.create_index('ix_ClienteTopicoBi_IdCliente', 'ClienteTopicoBi', ['IdCliente'], unique=False)
    # op.create_table('InscricoesEstaduais',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Cnpj', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    # sa.Column('InscricaoEstadual', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('NomeEstado', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('SiglaEstado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('IdIbge', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('Id', name='InscricoesEstaduais_pkey')
    # )
    # op.create_table('PerfilAplicacaoFuncao',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdPerfil', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('Aplicacao', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    # sa.Column('Funcao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdPerfil'], ['Perfil.Id'], name='PerfilAplicacaoFuncao_IdPerfil_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='PerfilAplicacaoFuncao_pkey')
    # )
    # op.create_table('SystemMessage',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('CodMessage', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    # sa.Column('DescMessage', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('TypeMessage', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    # sa.Column('FundLegal', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('Link', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('Id', name='SystemMessage_pkey')
    # )
    # op.create_table('Eventos',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('Evento', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('Descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('Id', name='Eventos_pkey')
    # )
    # op.create_table('ConsultaCnpj',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    # sa.Column('Nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('Porte', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('SiCad', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('OptSimples', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('DtOpSimples', sa.DATE(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('Id', name='ConsultaCnpj_pkey')
    # )
    # op.create_table('auth_group_permissions',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    # sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    # )
    # op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    # op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    # op.create_table('ItemEssencial',
    # sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    # sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('IdEmpresa', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('IdUsuarioAlteracao', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('CodigoProduto', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('IndEssencial', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['IdEmpresa'], ['Empresa.Id'], name='ItemEssencial_IdEmpresa_fkey'),
    # sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], name='ItemEssencial_IdUsuarioAlteracao_fkey'),
    # sa.PrimaryKeyConstraint('Id', name='ItemEssencial_pkey')
    # )
    # op.create_index('ix_ItemEssencial_IdEmpresa', 'ItemEssencial', ['IdEmpresa'], unique=False)
    # op.create_index('ix_ItemEssencial_CodigoProduto', 'ItemEssencial', ['CodigoProduto'], unique=False)
    # op.create_table('auth_user_user_permissions',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    # sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    # )
    # op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    # op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    # op.create_table('django_session',
    # sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    # sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    # )
    # op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    # op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    # op.create_table('t_e',
    # sa.Column('docs', sa.TEXT(), autoincrement=False, nullable=True)
    # )
    # op.create_table('auth_permission',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    # sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq')
    # )
    # op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    # op.create_table('django_admin_log',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    # sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    # )
    # op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    # op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    # ### end Alembic commands ###
