"""Tag Workflow

Revision ID: 2da42bdad915
Revises: 4899f9cccb83
Create Date: 2024-07-18 11:34:56.801477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2da42bdad915'
down_revision = '4899f9cccb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TagWorkflow',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('IdTagOrig', sa.String(length=40), nullable=True),
    sa.Column('IdTagDest', sa.UUID(), nullable=True),
    sa.Column('IdWorkflow', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdTagDest'], ['dlm.Tag.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.ForeignKeyConstraint(['IdWorkflow'], ['dlm.Workflow.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TagWorkflow', schema='dlm')
    # ### end Alembic commands ###
