"""add versao

Revision ID: 3104252a6bff
Revises: ec7c30fcb656
Create Date: 2024-08-08 12:09:56.184773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3104252a6bff'
down_revision = 'ec7c30fcb656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documento', sa.Column('Versao', sa.Integer(), nullable=True), schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Documento', 'Versao', schema='dlm')
