"""document table new columns

Revision ID: 35ac6d00308f
Revises: a33c73403ed4
Create Date: 2024-08-08 11:01:02.050247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35ac6d00308f'
down_revision = 'a33c73403ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documento', sa.Column('Numero', sa.String(length=12), nullable=True), schema='dlm')
    op.add_column('Documento', sa.Column('Revisao', sa.Integer(), nullable=True), schema='dlm')
    op.add_column('Documento', sa.Column('Patch', sa.Integer(), nullable=True), schema='dlm')
    op.add_column('Documento', sa.Column('Latest', sa.Boolean(), nullable=False), schema='dlm')
    op.add_column('Documento', sa.Column('Status', sa.String(length=20), nullable=True), schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Documento', 'Status', schema='dlm')
    op.drop_column('Documento', 'Latest', schema='dlm')
    op.drop_column('Documento', 'Patch', schema='dlm')
    op.drop_column('Documento', 'Revisao', schema='dlm')
    op.drop_column('Documento', 'Numero', schema='dlm')
    # ### end Alembic commands ###
