"""adding status field on ReconAnnotation table

Revision ID: 3a75621e4066
Revises: 9f5c7a2d92f5
Create Date: 2025-05-28 10:16:54.114764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a75621e4066'
down_revision = '9f5c7a2d92f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, create the enum type in PostgreSQL
    statusenum = postgresql.ENUM(
        'PROCESSING', 'READY', 'FAIL', 'COMPLETED', 'CLOSED', 
        'PENDING', 'OPEN', 'REQUEST_APPROVAL', 'APPROVED',
        name='statusenum',
        schema='ccs'
    )
    statusenum.create(op.get_bind())
    
    # Then add the column using the enum type
    op.add_column('ReconAnnotation', 
                  sa.Column('Status', statusenum, nullable=True), 
                  schema='ccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove the column first
    op.drop_column('ReconAnnotation', 'Status', schema='ccs')
    
    # Then drop the enum type
    statusenum = postgresql.ENUM(
        'PROCESSING', 'READY', 'FAIL', 'COMPLETED', 'CLOSED', 
        'PENDING', 'OPEN', 'REQUEST_APPROVAL', 'APPROVED',
        name='statusenum',
        schema='ccs'
    )
    statusenum.drop(op.get_bind())

    # ### end Alembic commands ###
