"""adding status field on ReconAnnotation table

Revision ID: 3a75621e4066
Revises: 9f5c7a2d92f5
Create Date: 2025-05-28 10:16:54.114764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a75621e4066'
down_revision = '9f5c7a2d92f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ReconAnnotation', sa.Column('Status', sa.Enum('PROCESSING', 'READY', 'FAIL', 'COMPLETED', 'CLOSED', 'PENDING', 'OPEN', 'REQUEST_APPROVAL', 'APPROVED', name='statusenum'), nullable=True), schema='ccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('ReconAnnotation', 'Status', schema='ccs')

    # ### end Alembic commands ###
