"""workflow palavrachavedocumento create table

Revision ID: 4899f9cccb83
Revises: 49b991b7d35c
Create Date: 2024-07-18 10:51:44.745461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4899f9cccb83'
down_revision = '49b991b7d35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workflow',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('IdTipoDocumento', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdTipoDocumento'], ['dlm.TipoDocumento.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    op.create_table('PalavraChaveDocumento',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('IdPalavraChave', sa.UUID(), nullable=True),
    sa.Column('IdDocumento', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdDocumento'], ['dlm.Documento.Id'], ),
    sa.ForeignKeyConstraint(['IdPalavraChave'], ['dlm.PalavraChave.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PalavraChaveDocumento', schema='dlm')
    op.drop_table('Workflow', schema='dlm')
    # ### end Alembic commands ###
