"""PalavraChave Documento create table

Revision ID: 49b991b7d35c
Revises: d63a9fd2c019
Create Date: 2024-07-18 10:08:24.383238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49b991b7d35c'
down_revision = 'd63a9fd2c019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PalavraChave',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('Palavra', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    op.create_table('Documento',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('IdTipoDocumento', sa.UUID(), nullable=True),
    sa.Column('Nome', sa.String(length=255), nullable=True),
    sa.Column('Key', sa.String(length=255), nullable=True),
    sa.Column('Observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['IdTipoDocumento'], ['dlm.TipoDocumento.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    op.create_table('TagDocumento',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('IdTag', sa.UUID(), nullable=True),
    sa.Column('IdDocumento', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdDocumento'], ['dlm.Documento.Id'], ),
    sa.ForeignKeyConstraint(['IdTag'], ['dlm.Tag.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    op.create_index(op.f('ix_dlm_TagDocumento_IdDocumento'), 'TagDocumento', ['IdDocumento'], unique=False, schema='dlm')
    op.create_index(op.f('ix_dlm_TagDocumento_IdTag'), 'TagDocumento', ['IdTag'], unique=False, schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dlm_TagDocumento_IdTag'), table_name='TagDocumento', schema='dlm')
    op.drop_index(op.f('ix_dlm_TagDocumento_IdDocumento'), table_name='TagDocumento', schema='dlm')
    op.drop_table('TagDocumento', schema='dlm')
    op.drop_table('Documento', schema='dlm')
    op.drop_table('PalavraChave', schema='dlm')
    # ### end Alembic commands ###
