"""other flight tables

Revision ID: 50692e5f4bc6
Revises: fe0038ecb904
Create Date: 2024-12-17 14:33:19.456115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50692e5f4bc6'
down_revision = 'fe0038ecb904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Configuration',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('TipoDeClasse', sa.String(length=10), nullable=False),
    sa.Column('pacote', sa.String(length=50), nullable=False),
    sa.Column('destinoPacket', sa.String(length=10), nullable=False),
    sa.Column('CódigoDoItem', sa.String(length=10), nullable=False),
    sa.Column('Descrição', sa.String(length=100), nullable=False),
    sa.Column('Provision1', sa.String(length=10), nullable=False),
    sa.Column('Provision2', sa.String(length=10), nullable=False),
    sa.Column('Tipo', sa.String(length=5), nullable=False),
    sa.Column('Svc', sa.Integer(), nullable=False),
    sa.Column('IdFligth', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdFligth'], ['ccs.Flight.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.create_table('DataSource',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('Source', sa.String(length=100), nullable=False),
    sa.Column('Page', sa.Integer(), nullable=False),
    sa.Column('IdFligth', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdFligth'], ['ccs.Flight.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.create_table('FlightDate',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('IdFligth', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdFligth'], ['ccs.Flight.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    
def downgrade():
    op.drop_table('FlightDate', schema='ccs')
    op.drop_table('DataSource', schema='ccs')
    op.drop_table('Configuration', schema='ccs')
    # ### end Alembic commands ###
