"""Adding BillingRecon, ErpInvoiceReport and Reconciliation tables

Revision ID: 52dfc5765ee8
Revises: 64a50262d1f4
Create Date: 2025-05-05 16:00:00.555760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52dfc5765ee8'
down_revision = '64a50262d1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BillingRecon',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('Facility', sa.String(), nullable=True),
    sa.Column('FltDate', sa.Date(), nullable=True),
    sa.Column('FltNo', sa.String(), nullable=True),
    sa.Column('FltInv', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.Column('ItemGroup', sa.String(), nullable=True),
    sa.Column('Itemcode', sa.String(), nullable=True),
    sa.Column('ItemDesc', sa.String(), nullable=True),
    sa.Column('AlBillCode', sa.String(), nullable=True),
    sa.Column('AlBillDesc', sa.String(), nullable=True),
    sa.Column('BillCatg', sa.String(), nullable=True),
    sa.Column('Unit', sa.String(), nullable=True),
    sa.Column('Pax', sa.String(), nullable=True),
    sa.Column('Qty', sa.String(), nullable=True),
    sa.Column('UnitPrice', sa.String(), nullable=True),
    sa.Column('TotalAmount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.create_table('ErpInvoiceReport',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('Supplier', sa.String(), nullable=True),
    sa.Column('FlightDate', sa.Date(), nullable=True),
    sa.Column('FlightNo', sa.String(), nullable=True),
    sa.Column('Dep', sa.String(), nullable=True),
    sa.Column('Arr', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.Column('InvoicedPax', sa.String(), nullable=True),
    sa.Column('ServiceCode', sa.String(), nullable=True),
    sa.Column('SupplierCode', sa.String(), nullable=True),
    sa.Column('ServiceDescription', sa.String(), nullable=True),
    sa.Column('Aircraft', sa.String(), nullable=True),
    sa.Column('Qty', sa.Integer(), nullable=True),
    sa.Column('UnitPrice', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('SubTotal', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Tax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('TotalIncTax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('ItemStatus', sa.String(), nullable=True),
    sa.Column('InvoiceStatus', sa.String(), nullable=True),
    sa.Column('InvoiceDate', sa.Date(), nullable=True),
    sa.Column('PaidDate', sa.Date(), nullable=True),
    sa.Column('FlightNoRed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.create_table('Reconciliation',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('AirSupplier', sa.String(), nullable=True),
    sa.Column('AirFlightDate', sa.Date(), nullable=True),
    sa.Column('AirFlightNo', sa.String(), nullable=True),
    sa.Column('AirDep', sa.String(), nullable=True),
    sa.Column('AirArr', sa.String(), nullable=True),
    sa.Column('AirClass', sa.String(), nullable=True),
    sa.Column('AirInvoicedPax', sa.String(), nullable=True),
    sa.Column('AirServiceCode', sa.String(), nullable=True),
    sa.Column('AirSupplierCode', sa.String(), nullable=True),
    sa.Column('AirServiceDescription', sa.String(), nullable=True),
    sa.Column('AirAircraft', sa.String(), nullable=True),
    sa.Column('AirQty', sa.Integer(), nullable=True),
    sa.Column('AirUnitPrice', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('AirSubTotal', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('AirTax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('AirTotalIncTax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('AirCurrency', sa.String(), nullable=True),
    sa.Column('AirItemStatus', sa.String(), nullable=True),
    sa.Column('AirInvoiceStatus', sa.String(), nullable=True),
    sa.Column('AirInvoiceDate', sa.Date(), nullable=True),
    sa.Column('AirPaidDate', sa.Date(), nullable=True),
    sa.Column('AirFlightNoRed', sa.String(), nullable=True),
    sa.Column('CatFacility', sa.String(), nullable=True),
    sa.Column('CatFltDate', sa.Date(), nullable=True),
    sa.Column('CatFltNo', sa.String(), nullable=True),
    sa.Column('CatFltInv', sa.String(), nullable=True),
    sa.Column('CatClass', sa.String(), nullable=True),
    sa.Column('CatItemGroup', sa.String(), nullable=True),
    sa.Column('CatItemcode', sa.String(), nullable=True),
    sa.Column('CatItemDesc', sa.String(), nullable=True),
    sa.Column('CatAlBillCode', sa.String(), nullable=True),
    sa.Column('CatAlBillDesc', sa.String(), nullable=True),
    sa.Column('CatBillCatg', sa.String(), nullable=True),
    sa.Column('CatUnit', sa.String(), nullable=True),
    sa.Column('CatPax', sa.Integer(), nullable=True),
    sa.Column('CatQty', sa.Integer(), nullable=True),
    sa.Column('CatUnitPrice', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('CatTotalAmount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Air', sa.String(length=3), nullable=True),
    sa.Column('Cat', sa.String(length=3), nullable=True),
    sa.Column('DifQty', sa.String(length=3), nullable=True),
    sa.Column('DifPrice', sa.String(length=3), nullable=True),
    sa.Column('AmountDif', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('QtyDif', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.alter_column('Configuration', 'TipoDeClasse',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               schema='ccs')
    op.alter_column('Configuration', 'Provision1',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               schema='ccs')
    op.alter_column('Configuration', 'Provision2',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               schema='ccs')
    op.alter_column('Configuration', 'Tipo',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               schema='ccs')
    op.alter_column('Configuration', 'Svc',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ccs')
    op.alter_column('DataSource', 'IdFlight',
               existing_type=sa.UUID(),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'Facility',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'Organization',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'PulledDate',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'RunDate',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'FacOrg',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'SpcNr',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'SpcDsc',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'ActCatNm',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'PrsStsCd',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'PrcEffDt',
               existing_type=sa.DATE(),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'PrcDisDt',
               existing_type=sa.DATE(),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'PrcCurCd',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'PktNr',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'PktNm',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='ccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PriceReport', 'PktNm',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'PktNr',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'PrcCurCd',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'PrcDisDt',
               existing_type=sa.DATE(),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'PrcEffDt',
               existing_type=sa.DATE(),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'PrsStsCd',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'ActCatNm',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'SpcDsc',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'SpcNr',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'FacOrg',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'RunDate',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'PulledDate',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'Organization',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'Facility',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='ccs')
    op.alter_column('DataSource', 'IdFlight',
               existing_type=sa.UUID(),
               nullable=True,
               schema='ccs')
    op.alter_column('Configuration', 'Svc',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'Tipo',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'Provision2',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'Provision1',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'TipoDeClasse',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='ccs')
    
    op.drop_table('Reconciliation', schema='ccs')
    op.drop_table('ErpInvoiceReport', schema='ccs')
    op.drop_table('BillingRecon', schema='ccs')
    # ### end Alembic commands ###
