"""Adjust new fields and field names

Revision ID: 64a50262d1f4
Revises: cc7e3051d041
Create Date: 2025-04-24 10:17:40.433191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64a50262d1f4'
down_revision = 'cc7e3051d041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('Configuration', sa.Column('Pacote', sa.String(length=50), nullable=True), schema='ccs')
    op.add_column('Configuration', sa.Column('DestinoPacket', sa.String(length=10), nullable=True), schema='ccs')
    op.add_column('Configuration', sa.Column('CodigoDoItem', sa.String(length=10), nullable=True), schema='ccs')
    op.add_column('Configuration', sa.Column('Descricao', sa.String(length=100), nullable=True), schema='ccs')
    op.add_column('Configuration', sa.Column('IdFlight', sa.UUID(), nullable=True), schema='ccs')
    op.drop_constraint('Configuration_IdFligth_fkey', 'Configuration', schema='ccs', type_='foreignkey')
    op.create_foreign_key(None, 'Configuration', 'Flight', ['IdFlight'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.drop_column('Configuration', 'CódigoDoItem', schema='ccs')
    op.drop_column('Configuration', 'pacote', schema='ccs')
    op.drop_column('Configuration', 'Descrição', schema='ccs')
    op.drop_column('Configuration', 'destinoPacket', schema='ccs')
    op.drop_column('Configuration', 'IdFligth', schema='ccs')
    op.add_column('Flight', sa.Column('Meal', sa.Integer(), nullable=True), schema='ccs')
    op.add_column('Flight', sa.Column('Tray', sa.Integer(), nullable=True), schema='ccs')
    op.add_column('Flight', sa.Column('QtdPax', sa.Integer(), nullable=True), schema='ccs')
    op.add_column('Flight', sa.Column('ConfiguracaoId', sa.UUID(), nullable=True), schema='ccs')
    op.add_column('Flight', sa.Column('FlightDateId', sa.UUID(), nullable=True), schema='ccs')
    op.add_column('Flight', sa.Column('DataVoo', sa.Date(), nullable=True), schema='ccs')
    op.add_column('Flight', sa.Column('FlightReportId', sa.UUID(), nullable=True), schema='ccs')
    op.create_foreign_key(None, 'Flight', 'Configuration', ['ConfiguracaoId'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.create_foreign_key(None, 'Flight', 'FlightDate', ['FlightDateId'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.create_foreign_key(None, 'Flight', 'PriceReport', ['FlightReportId'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.add_column('FlightDate', sa.Column('DataVoo', sa.Date(), nullable=True), schema='ccs')
    op.add_column('FlightDate', sa.Column('IdFlight', sa.UUID(), nullable=True), schema='ccs')
    op.drop_constraint('FlightDate_IdFligth_fkey', 'FlightDate', schema='ccs', type_='foreignkey')
    op.create_foreign_key(None, 'FlightDate', 'Flight', ['IdFlight'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.drop_column('FlightDate', 'Date', schema='ccs')
    op.drop_column('FlightDate', 'IdFligth', schema='ccs')
    op.add_column('InvoiceHistory', sa.Column('Airline', sa.String(length=50), nullable=True), schema='ccs')
    op.add_column('InvoiceHistory', sa.Column('Currency', sa.String(length=10), nullable=True), schema='ccs')
    op.add_column('InvoiceHistory', sa.Column('ReconStatus', sa.String(length=20), nullable=True), schema='ccs')
    op.add_column('InvoiceHistory', sa.Column('BillingReference', sa.String(length=100), nullable=True), schema='ccs')
    op.add_column('InvoiceHistory', sa.Column('ImportedAt', sa.DateTime(), nullable=True), schema='ccs')
    op.drop_index('invoicehistory_sourcename_idx', table_name='InvoiceHistory', schema='ccs')
    op.alter_column('PriceReport', 'TotAmt',
               existing_type=sa.NUMERIC(),
               nullable=True,
               schema='ccs')
    op.alter_column('PriceReport', 'LbrAmt',
               existing_type=sa.NUMERIC(),
               nullable=True,
               schema='ccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PriceReport', 'LbrAmt',
               existing_type=sa.NUMERIC(),
               nullable=False,
               schema='ccs')
    op.alter_column('PriceReport', 'TotAmt',
               existing_type=sa.NUMERIC(),
               nullable=False,
               schema='ccs')
    op.create_index('invoicehistory_sourcename_idx', 'InvoiceHistory', ['SourceName'], unique=False, schema='ccs')
    op.drop_column('InvoiceHistory', 'ImportedAt', schema='ccs')
    op.drop_column('InvoiceHistory', 'BillingReference', schema='ccs')
    op.drop_column('InvoiceHistory', 'ReconStatus', schema='ccs')
    op.drop_column('InvoiceHistory', 'Currency', schema='ccs')
    op.drop_column('InvoiceHistory', 'Airline', schema='ccs')
    op.add_column('FlightDate', sa.Column('IdFligth', sa.UUID(), autoincrement=False, nullable=True), schema='ccs')
    op.add_column('FlightDate', sa.Column('Date', sa.DATE(), autoincrement=False, nullable=True), schema='ccs')
    op.drop_constraint(None, 'FlightDate', schema='ccs', type_='foreignkey')
    op.create_foreign_key('FlightDate_IdFligth_fkey', 'FlightDate', 'Flight', ['IdFligth'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.drop_column('FlightDate', 'IdFlight', schema='ccs')
    op.drop_column('FlightDate', 'DataVoo', schema='ccs')
    op.drop_constraint(None, 'Flight', schema='ccs', type_='foreignkey')
    op.drop_constraint(None, 'Flight', schema='ccs', type_='foreignkey')
    op.drop_constraint(None, 'Flight', schema='ccs', type_='foreignkey')
    op.drop_column('Flight', 'FlightReportId', schema='ccs')
    op.drop_column('Flight', 'DataVoo', schema='ccs')
    op.drop_column('Flight', 'FlightDateId', schema='ccs')
    op.drop_column('Flight', 'ConfiguracaoId', schema='ccs')
    op.drop_column('Flight', 'QtdPax', schema='ccs')
    op.drop_column('Flight', 'Tray', schema='ccs')
    op.drop_column('Flight', 'Meal', schema='ccs')
    op.add_column('DataSource', sa.Column('IdFligth', sa.UUID(), autoincrement=False, nullable=True), schema='ccs')
    op.drop_constraint(None, 'DataSource', schema='ccs', type_='foreignkey')
    op.create_foreign_key('DataSource_IdFligth_fkey', 'DataSource', 'Flight', ['IdFligth'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.add_column('Configuration', sa.Column('IdFligth', sa.UUID(), autoincrement=False, nullable=True), schema='ccs')
    op.add_column('Configuration', sa.Column('destinoPacket', sa.VARCHAR(length=10), autoincrement=False, nullable=False), schema='ccs')
    op.add_column('Configuration', sa.Column('Descrição', sa.VARCHAR(length=100), autoincrement=False, nullable=False), schema='ccs')
    op.add_column('Configuration', sa.Column('pacote', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='ccs')
    op.add_column('Configuration', sa.Column('CódigoDoItem', sa.VARCHAR(length=10), autoincrement=False, nullable=False), schema='ccs')
    op.drop_constraint(None, 'Configuration', schema='ccs', type_='foreignkey')
    op.create_foreign_key('Configuration_IdFligth_fkey', 'Configuration', 'Flight', ['IdFligth'], ['Id'], source_schema='ccs', referent_schema='ccs')
    op.alter_column('Configuration', 'Svc',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'Tipo',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'Provision2',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'Provision1',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='ccs')
    op.alter_column('Configuration', 'TipoDeClasse',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               schema='ccs')
    op.drop_column('Configuration', 'IdFlight', schema='ccs')
    op.drop_column('Configuration', 'Descricao', schema='ccs')
    op.drop_column('Configuration', 'CodigoDoItem', schema='ccs')
    op.drop_column('Configuration', 'DestinoPacket', schema='ccs')
    op.drop_column('Configuration', 'Pacote', schema='ccs')
    # ### end Alembic commands ###
