"""rename CateringInvoiceReport and ERPInvoice tables to CateringInvoiceReport and AirCompanyInvoiceReport and adding FlightNumberMapping and FlightClassMapping tables

Revision ID: 72356c753c43
Revises: 52dfc5765ee8
Create Date: 2025-05-22 09:09:17.987541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72356c753c43'
down_revision = '52dfc5765ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AirCompanyInvoiceReport',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('Supplier', sa.String(), nullable=True),
    sa.Column('FlightDate', sa.Date(), nullable=True),
    sa.Column('FlightNo', sa.String(), nullable=True),
    sa.Column('Dep', sa.String(), nullable=True),
    sa.Column('Arr', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.Column('InvoicedPax', sa.String(), nullable=True),
    sa.Column('ServiceCode', sa.String(), nullable=True),
    sa.Column('SupplierCode', sa.String(), nullable=True),
    sa.Column('ServiceDescription', sa.String(), nullable=True),
    sa.Column('Aircraft', sa.String(), nullable=True),
    sa.Column('Qty', sa.Integer(), nullable=True),
    sa.Column('UnitPrice', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('SubTotal', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Tax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('TotalIncTax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('Currency', sa.String(), nullable=True),
    sa.Column('ItemStatus', sa.String(), nullable=True),
    sa.Column('InvoiceStatus', sa.String(), nullable=True),
    sa.Column('InvoiceDate', sa.Date(), nullable=True),
    sa.Column('PaidDate', sa.Date(), nullable=True),
    sa.Column('FlightNoRed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.create_table('CateringInvoiceReport',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('Facility', sa.String(), nullable=True),
    sa.Column('FltDate', sa.Date(), nullable=True),
    sa.Column('FltNo', sa.String(), nullable=True),
    sa.Column('FltInv', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.Column('ItemGroup', sa.String(), nullable=True),
    sa.Column('Itemcode', sa.String(), nullable=True),
    sa.Column('ItemDesc', sa.String(), nullable=True),
    sa.Column('AlBillCode', sa.String(), nullable=True),
    sa.Column('AlBillDesc', sa.String(), nullable=True),
    sa.Column('BillCatg', sa.String(), nullable=True),
    sa.Column('Unit', sa.String(), nullable=True),
    sa.Column('Pax', sa.String(), nullable=True),
    sa.Column('Qty', sa.String(), nullable=True),
    sa.Column('UnitPrice', sa.String(), nullable=True),
    sa.Column('TotalAmount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.create_table('FlightClassMapping',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('PromeusClass', sa.String(), nullable=True),
    sa.Column('InflairClass', sa.String(), nullable=True),
    sa.Column('ItemGroup', sa.String(), nullable=True),
    sa.Column('ItemCode', sa.String(), nullable=True),
    sa.Column('ItemDesc', sa.String(), nullable=True),
    sa.Column('ALBillCode', sa.String(), nullable=True),
    sa.Column('ALBillDesc', sa.String(), nullable=True),
    sa.Column('BillCatg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    op.create_table('FlightNumberMapping',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('AirCompanyFlightNumber', sa.String(), nullable=True),
    sa.Column('CateringFlightNumber', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AirCompanyInvoiceReport',
    sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Supplier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('FlightDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('FlightNo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Dep', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Arr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('InvoicedPax', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ServiceCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('SupplierCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ServiceDescription', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Aircraft', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('UnitPrice', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('SubTotal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('Tax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('TotalIncTax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('Currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ItemStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('InvoiceStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('InvoiceDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('PaidDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('FlightNoRed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='ErpInvoiceReport_pkey'),
    schema='ccs'
    )
    op.create_table('CateringInvoiceReport',
    sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Facility', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('FltDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('FltNo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('FltInv', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ItemGroup', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Itemcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ItemDesc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('AlBillCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('AlBillDesc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('BillCatg', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Pax', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Qty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('UnitPrice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('TotalAmount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='BillingRecon_pkey'),
    schema='ccs'
    )
    op.drop_table('FlightNumberMapping', schema='ccs')
    op.drop_table('FlightClassMapping', schema='ccs')
    op.drop_table('CateringInvoiceReport', schema='ccs')
    op.drop_table('AirCompanyInvoiceReport', schema='ccs')
    # ### end Alembic commands ###
