"""chenge workflow relacions

Revision ID: 726b43d61129
Revises: 74094251851d
Create Date: 2024-07-30 11:38:51.687933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '726b43d61129'
down_revision = '74094251851d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TipoDocumento', sa.Column('IdWorkflow', sa.UUID(), nullable=True), schema='dlm')
    op.create_foreign_key(None, 'TipoDocumento', 'Workflow', ['IdWorkflow'], ['Id'], source_schema='dlm', referent_schema='dlm')
    op.drop_constraint('Workflow_IdTipoDocumento_fkey', 'Workflow', schema='dlm', type_='foreignkey')
    op.drop_column('Workflow', 'IdTipoDocumento', schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workflow', sa.Column('IdTipoDocumento', sa.UUID(), autoincrement=False, nullable=True), schema='dlm')
    op.create_foreign_key('Workflow_IdTipoDocumento_fkey', 'Workflow', 'TipoDocumento', ['IdTipoDocumento'], ['Id'], source_schema='dlm', referent_schema='dlm')
    op.drop_constraint(None, 'TipoDocumento', schema='dlm', type_='foreignkey')
    op.drop_column('TipoDocumento', 'IdWorkflow', schema='dlm')
    # ### end Alembic commands ###
