"""adding ReconAnnotation table

Revision ID: 9f5c7a2d92f5
Revises: 72356c753c43
Create Date: 2025-05-27 15:44:08.396184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f5c7a2d92f5'
down_revision = '72356c753c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ReconAnnotation',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('ReconciliationId', sa.UUID(), nullable=False),
    sa.Column('Annotation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ReconciliationId'], ['ccs.Reconciliation.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReconAnnotation', schema='ccs')
    # ### end Alembic commands ###
