"""tag aviso table

Revision ID: a33c73403ed4
Revises: cd5f3259d09c
Create Date: 2024-08-01 10:56:35.450670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a33c73403ed4'
down_revision = 'cd5f3259d09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TagAviso',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('Aviso', sa.Text(), nullable=True),
    sa.Column('IdTag', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['IdTag'], ['dlm.Tag.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TagAviso', schema='dlm')
    # ### end Alembic commands ###
