"""name workflow

Revision ID: be3ff5d1fc6c
Revises: 726b43d61129
Create Date: 2024-07-30 12:10:24.843636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be3ff5d1fc6c'
down_revision = '726b43d61129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Workflow', sa.Column('Nome', sa.String(length=255), nullable=True), schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Workflow', 'Nome', schema='dlm')
    # ### end Alembic commands ###
