"""add SorceFlie to priceReport table

Revision ID: cc7e3051d041
Revises: 133bffe21e3e
Create Date: 2025-02-11 15:26:47.976363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc7e3051d041'
down_revision = '133bffe21e3e'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('PriceReport', sa.Column('SourceFile', sa.String(length=255), nullable=True), schema='ccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PriceReport', 'SourceFile', schema='ccs')
