"""corrections workflow

Revision ID: cd5f3259d09c
Revises: f84fd5cbcfbc
Create Date: 2024-08-01 07:54:56.537947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd5f3259d09c'
down_revision = 'f84fd5cbcfbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tag', sa.Column('IdTipoDocumento', sa.UUID(), nullable=True), schema='dlm')
    op.create_index(op.f('ix_dlm_Tag_IdTipoDocumento'), 'Tag', ['IdTipoDocumento'], unique=False, schema='dlm')
    op.create_foreign_key(None, 'Tag', 'TipoDocumento', ['IdTipoDocumento'], ['Id'], source_schema='dlm', referent_schema='dlm')
    op.add_column('TagWorkflow', sa.Column('IdTipoDocumento', sa.UUID(), nullable=True), schema='dlm')
    op.create_index(op.f('ix_dlm_TagWorkflow_IdTipoDocumento'), 'TagWorkflow', ['IdTipoDocumento'], unique=False, schema='dlm')
    op.drop_constraint('TagWorkflow_IdWorkflow_fkey', 'TagWorkflow', schema='dlm', type_='foreignkey')
    op.create_foreign_key(None, 'TagWorkflow', 'TipoDocumento', ['IdTipoDocumento'], ['Id'], source_schema='dlm', referent_schema='dlm')
    op.drop_column('TagWorkflow', 'IdWorkflow', schema='dlm')
    op.add_column('TipoDocumento', sa.Column('Sigla', sa.String(length=6), nullable=True), schema='dlm')
    op.drop_constraint('TipoDocumento_IdWorkflow_fkey', 'TipoDocumento', schema='dlm', type_='foreignkey')
    op.drop_column('TipoDocumento', 'IdWorkflow', schema='dlm')
    op.drop_table('Workflow', schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TipoDocumento', sa.Column('IdWorkflow', sa.UUID(), autoincrement=False, nullable=True), schema='dlm')
    op.create_foreign_key('TipoDocumento_IdWorkflow_fkey', 'TipoDocumento', 'Workflow', ['IdWorkflow'], ['Id'], source_schema='dlm', referent_schema='dlm')
    op.drop_column('TipoDocumento', 'Sigla', schema='dlm')
    op.add_column('TagWorkflow', sa.Column('IdWorkflow', sa.UUID(), autoincrement=False, nullable=True), schema='dlm')
    op.drop_constraint(None, 'TagWorkflow', schema='dlm', type_='foreignkey')
    op.create_foreign_key('TagWorkflow_IdWorkflow_fkey', 'TagWorkflow', 'Workflow', ['IdWorkflow'], ['Id'], source_schema='dlm', referent_schema='dlm')
    op.drop_index(op.f('ix_dlm_TagWorkflow_IdTipoDocumento'), table_name='TagWorkflow', schema='dlm')
    op.drop_column('TagWorkflow', 'IdTipoDocumento', schema='dlm')
    op.drop_constraint(None, 'Tag', schema='dlm', type_='foreignkey')
    op.drop_index(op.f('ix_dlm_Tag_IdTipoDocumento'), table_name='Tag', schema='dlm')
    op.drop_column('Tag', 'IdTipoDocumento', schema='dlm')
    op.create_table('Workflow',
    sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('DataCriacao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('DataAtualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Excluido', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('Nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], name='Workflow_IdUsuarioAlteracao_fkey'),
    sa.PrimaryKeyConstraint('Id', name='Workflow_pkey'),
    schema='dlm'
    )
    # ### end Alembic commands ###
