"""Criacao tabelas tipo documento e tag

Revision ID: d63a9fd2c019
Revises: 
Create Date: 2024-07-18 09:35:30.700734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd63a9fd2c019'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('IdEmpresa', sa.UUID(), nullable=True),
    sa.Column('Nome', sa.String(length=50), nullable=True),
    sa.Column('Cor', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['IdEmpresa'], ['Empresa.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    op.create_index(op.f('ix_dlm_Tag_IdEmpresa'), 'Tag', ['IdEmpresa'], unique=False, schema='dlm')
    op.create_table('TipoDocumento',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('IdEmpresa', sa.UUID(), nullable=True),
    sa.Column('Extensao', sa.String(length=100), nullable=True),
    sa.Column('Nome', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['IdEmpresa'], ['Empresa.Id'], ),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='dlm'
    )
    op.create_index(op.f('ix_dlm_TipoDocumento_IdEmpresa'), 'TipoDocumento', ['IdEmpresa'], unique=False, schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dlm_TipoDocumento_IdEmpresa'), table_name='TipoDocumento', schema='dlm')
    op.drop_table('TipoDocumento', schema='dlm')
    op.drop_index(op.f('ix_dlm_Tag_IdEmpresa'), table_name='Tag', schema='dlm')
    op.drop_table('Tag', schema='dlm')
    # ### end Alembic commands ###
