"""Add BillingInvoiceTotalDiference table

Revision ID: ddaaf2df7883
Revises: 065f043a38d5
Create Date: 2025-06-30 11:01:18.143858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddaaf2df7883'
down_revision = '065f043a38d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BillingInvoiceTotalDifference',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('AnalysedField', sa.String(), nullable=False),
    sa.Column('AnalysedItem', sa.String(), nullable=False),
    sa.Column('FlightDate', sa.Date(), nullable=False),
    sa.Column('TotalAmount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BillingInvoiceTotalDifference', schema='ccs')
    # ### end Alembic commands ###
