"""remove versao

Revision ID: ec7c30fcb656
Revises: 35ac6d00308f
Create Date: 2024-08-08 11:54:47.081194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec7c30fcb656'
down_revision = '35ac6d00308f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Documento', 'Versao', schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documento', sa.Column('Versao', sa.VARCHAR(length=10), autoincrement=False, nullable=True), schema='dlm')
    # ### end Alembic commands ###
