"""tag workflow new columns

Revision ID: f84fd5cbcfbc
Revises: be3ff5d1fc6c
Create Date: 2024-07-30 16:58:49.801019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f84fd5cbcfbc'
down_revision = 'be3ff5d1fc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TagWorkflow', sa.Column('Sequencial', sa.Integer(), nullable=True), schema='dlm')
    op.add_column('TagWorkflow', sa.Column('Validacao', sa.Boolean(), nullable=True), schema='dlm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TagWorkflow', 'Validacao', schema='dlm')
    op.drop_column('TagWorkflow', 'Sequencial', schema='dlm')
    # ### end Alembic commands ###
