"""Initial migration

Revision ID: fe0038ecb904
Revises: 5ccfb039deeb
Create Date: 2024-12-17 14:10:58.084065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe0038ecb904'
down_revision = '5ccfb039deeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flight',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('DataCriacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('DataAtualizacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), nullable=False),
    sa.Column('Excluido', sa.Boolean(), nullable=False),
    sa.Column('IdUsuarioAlteracao', sa.UUID(), nullable=True),
    sa.Column('EmpresaAerea', sa.String(length=50), nullable=False),
    sa.Column('Periodo', sa.String(length=30), nullable=True),
    sa.Column('Unidade', sa.String(length=10), nullable=False),
    sa.Column('Ciclo', sa.Integer(), nullable=False),
    sa.Column('VrVoo', sa.Integer(), nullable=False),
    sa.Column('Origem', sa.String(length=10), nullable=False),
    sa.Column('Destino', sa.String(length=10), nullable=False),
    sa.Column('HoraPartida', sa.String(length=10), nullable=False),
    sa.Column('HoraChegada', sa.String(length=10), nullable=False),
    sa.Column('Aeronave', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdUsuarioAlteracao'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    schema='ccs'
    )

def downgrade():
    op.drop_table('Flight', schema='ccs')
    # ### end Alembic commands ###
