FROM public.ecr.aws/lambda/python:3.8

COPY app/analyse_data_api/requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt

COPY app/analyse_data_api/analyse_data_api.py ${LAMBDA_TASK_ROOT}

COPY services/ ${LAMBDA_TASK_ROOT}/services/
COPY repositories/ ${LAMBDA_TASK_ROOT}/repositories/
COPY models/ ${LAMBDA_TASK_ROOT}/models/
COPY enums/ ${LAMBDA_TASK_ROOT}/enums/
COPY common/ ${LAMBDA_TASK_ROOT}/common/

CMD ["analyse_data_api.main"]
